routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\ProfileController;


use App\Http\Controllers\ProductController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
//home
// Route::get('/home', [HomeController::class, 'index'])->name('home.index');
Route::get('/', [HomeController::class, 'index'])->name('home.index');

Route::get('/pay', [CartController::class, 'pay'])->name('cart.pay');

//homedetail

//cart

//search
Route::group(['prefix' => 'product', 'as' => 'product.'], function () {
    Route::get('/', [ProductController::class, 'index'])->name('index');
    
});
//shopping

Route::group(['prefix' => 'product', 'as' => 'product.'], function () {
    Route::get('/detail/{id}', [ProductController::class, 'detail'])->name('detail');
    
});

Route::group(['prefix' => 'cart', 'as' => 'cart.'], function () {
    Route::get('/', [CartController::class, 'index'])->name('index');
    Route::post('/{id}/add', [CartController::class, 'addCart'])->name('add-cart');

    Route::group(['prefix' => 'checkout', 'as' => 'checkout.'], function () {
        // Route for shipping-information
        Route::get('/shipping-information', [CartController::class, 'shippingInformation'])->name('shipping-information');
        Route::post('/handle-shipping-information', [CartController::class, 'handleShippingInformation'])->name('handle-shipping-information');

        // Route for payment-method
        Route::get('/payment-method', [CartController::class, 'paymentMethod'])->name('payment-method');

        // Route for checkout-order
        Route::post('/checkout-order', [CartController::class, 'checkoutOrder'])->name('checkout-order');

        // Route for thank-you
        Route::get('/thank-you', [CartController::class, 'thankYou'])->name('thank-you');
    });
});



Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

require __DIR__.'/auth.php';


Route::group(['prefix' => 'cart', 'as' => 'cart.'], function () {
    Route::get('/', [CartController::class, 'index'])->name('index');
    Route::post('/{id}/add', [CartController::class, 'addCart'])->name('add-cart');
    Route::put('/{id}/update-quantity', [CartController::class, 'updateQuantity'])->name('update-quantity');
    Route::delete('/{id}/remove-product-in-cart', [CartController::class, 'removeProductInCart'])->name('remove-product-in-cart');
});
Route::get('/my-profile', [ProfileController::class, 'myProfile'])->name('my-profile');

Route::post('post/comment/{id}', [ProductController::class, 'store'])
        ->name('post.comment');

resources/views/cart/checkouts/parts/payment_method_info.blade.php
<section class="payment-method-info">
    <form action="{{ route('cart.checkout.checkout-order') }}" method="POST">
        @csrf
        
        <p>Phương thức vận chuyển</p>
        <div class="d-flex justify-content-between mb-2 border p-2">
            <div>
                <input type="radio" name="shipping_method" value="1" checked id="shipping-method-1">
                <label for="shipping-method-1">Giao hàng tận nơi</label>
                <input type="hidden" name="shipping_fee" value="0">
                @error('shipping_method')
                    <div class="text-danger">{{ $message }}</div>
                @enderror
            </div>
            <div>
                0đ
            </div>
        </div>

        {{-- Phương thức thanh toán --}}
        <p class="mt-5"><label class="required">Phương thức thanh toán</label></p>
         <div class="mb-3 border p-2">
             <input type="radio" name="payment_method_id" value="1" checked id="payment-method-1">
             <label for="payment-method-1">Thanh toán khi giao hàng (COD)</label>
         </div>
         <div class="mb-3 border p-2">
             <input type="radio" name="payment_method_id" value="2" id="payment-method-2" disabled>
             <label for="payment-method-2">Chuyển khoản qua ngân hàng</label>
         </div>
         @error('payment_method_id')
            <div class="text-danger">{{ $message }}</div>
         @enderror

         <div class="d-flex justify-content-between">
             <a href="{{ route('cart.checkout.shipping-information') }}">Trở lại thông tin vận chuyển</a>
             <button type="submit" class="btn btn-primary">Xác nhận đặt hàng</button>
         </div>

    </form>
</section>

resources/views/cart/checkouts/parts/product_list.blade.php
@if (!empty($carts))
    <div class="">
        @foreach($carts as $cart)
            @php $productInfo = $cart['product_info']; @endphp
            <div class="">
                <div class="">
                    <div class="" >
                        <div class="w-24">
                            <span class="">{{ $cart['cart_quantity'] }}</span>
                            <img src="{{ $productInfo->thumbnail }}" alt="{{ $productInfo->name }}" class="">
                        </div>
                        <div class="">
                            <p class="px-2">{{ $productInfo->name }}</p>
                        </div>
                    </div>
                    <div >
                        @if($cart['amount_discount'])
                            <div class="">
                                <span class="">
                                    {!! ($cart['amount_discount']) !!}</span>&nbsp;&nbsp;&nbsp;
                                <span class="">
                                    {!! ($cart['amount']) !!}</span>
                            </div>
                        @else
                            <div class="">
                                <span class="">
                                    {!! ($cart['amount']) !!}</span>
                            </div>
                        @endif
                    </div>
                </div>
            </div>
        @endforeach
            
        <hr>

        <div class="cart-info">
            <div class="d-flex justify-content-between">
                <label>Tạm tính</label>
                @if($total_amount_discount != $total_amount)
                    <span>
                        <span class="sale-price">{{ ($total_amount_discount) }}</span>
                        <span class="sale-price-through">{{ ($total_amount) }}</span>
                    </span>
                @else
                    <span>
                        <span class="sale-price">{{ ($total_amount_discount) }}</span>
                    </span>
                @endif
            </div>
            <div class="d-flex justify-content-between">
                <label>Phí shíp</label>
                <span>Miễn phí</span>
            </div>
        </div>

        <hr>

        <div class="d-flex justify-content-between">
            <label class="fw-bold fs-1">Tổng tiền</label>
            @if($total_amount_discount != $total_amount)
                <span>
                    <span class="fw-bold fs-1 sale-price">{{ ($total_amount_discount) }}</span>
                    <span class="sale-price-through">{{ ($total_amount) }}</span>
                </span>
            @else
                <span>
                    <span class="fw-bold fs-1 sale-price">{{ ($total_amount) }}</span>
                </span>
            @endif
        </div>
    </div>
@endif

resources/views/cart/checkouts/parts/shipping_information_info.blade.php
<section class="payment-method-info">

    <form action="{{ route('cart.checkout.handle-shipping-information') }}" method="POST">
        @csrf

        <div class="row">
            <div class="col-md-6">
                <div class="mb-3">
                    <label class="form-label"><label class="required">Họ và tên</label></label>
                    @php
                     $fullname = isset($cartShippingInfo['fullname']) ? $cartShippingInfo['fullname'] : null;
                    @endphp
                    <input type="text" name="fullname" value="{{ old('fullname', $fullname) }}" class="form-control" placeholder="">
                    
                 </div>
            </div>
            <div class="col-md-6">
                <div class="mb-3">
                   <label class="form-label"><label class="required">Số điện thoại</label></label>
                   @php
                     $phone = isset($cartShippingInfo['phone']) ? $cartShippingInfo['phone'] : null;
                    @endphp
                   <input type="number" name="phone" value="{{ old('phone', $phone) }}" class="form-control" placeholder="">
                   
                </div>
            </div>
        </div>

         <div class="mb-3">
            <label class="form-label required">Email</label>
            @php
            $email = isset($cartShippingInfo['email']) ? $cartShippingInfo['email'] : null;
           @endphp
            <input type="email" name="email" value="{{ old('email', $email) }}" class="form-control" placeholder="">
            
         </div>

         <div class="mb-3">
            <label class="form-label"><label class="required">Địa chỉ giao hàng</label></label>
            @php
                $address = isset($cartShippingInfo['address']) ? $cartShippingInfo['address'] : null;
            @endphp
            <input type="text" name="address" value="{{ old('address', $address) }}" class="form-control" placeholder="">
           
         </div>

         <div class="mb-3">
            <label class="form-label">Để lại lời nhắn</label>
            @php
                $comment = isset($cartShippingInfo['comment']) ? $cartShippingInfo['comment'] : null;
            @endphp
            <textarea name="comment" class="form-control" rows="2">{{ old('comment', $comment) }}</textarea>
           
         </div>

         <div class="d-flex justify-content-between">
             <a href="{{ route('cart.index') }}">Giỏ hàng</a>
             <button type="submit" class="btn btn-primary">Xác nhận thông tin</button>
         </div>
    </form>
</section>