routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\CartController;
use App\Http\Controllers\ProfileController;


use App\Http\Controllers\ProductController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
//home
// Route::get('/home', [HomeController::class, 'index'])->name('home.index');
Route::get('/', [HomeController::class, 'index'])->name('home.index');

Route::get('/pay', [CartController::class, 'pay'])->name('cart.pay');

//homedetail

//cart

//search
Route::group(['prefix' => 'product', 'as' => 'product.'], function () {
    Route::get('/', [ProductController::class, 'index'])->name('index');
    
});
//shopping

Route::group(['prefix' => 'product', 'as' => 'product.'], function () {
    Route::get('/detail/{id}', [ProductController::class, 'detail'])->name('detail');
    
});

Route::group(['prefix' => 'cart', 'as' => 'cart.'], function () {
    Route::get('/', [CartController::class, 'index'])->name('index');
    Route::post('/{id}/add', [CartController::class, 'addCart'])->name('add-cart');

    Route::group(['prefix' => 'checkout', 'as' => 'checkout.'], function () {
        // Route for shipping-information
        Route::get('/shipping-information', [CartController::class, 'shippingInformation'])->name('shipping-information');
        Route::post('/handle-shipping-information', [CartController::class, 'handleShippingInformation'])->name('handle-shipping-information');

        // Route for payment-method
        Route::get('/payment-method', [CartController::class, 'paymentMethod'])->name('payment-method');

        // Route for checkout-order
        Route::post('/checkout-order', [CartController::class, 'checkoutOrder'])->name('checkout-order');

        // Route for thank-you
        Route::get('/thank-you', [CartController::class, 'thankYou'])->name('thank-you');
    });
});



Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth', 'verified'])->name('dashboard');

require __DIR__.'/auth.php';


Route::group(['prefix' => 'cart', 'as' => 'cart.'], function () {
    Route::get('/', [CartController::class, 'index'])->name('index');
    Route::post('/{id}/add', [CartController::class, 'addCart'])->name('add-cart');
    Route::put('/{id}/update-quantity', [CartController::class, 'updateQuantity'])->name('update-quantity');
    Route::delete('/{id}/remove-product-in-cart', [CartController::class, 'removeProductInCart'])->name('remove-product-in-cart');
});
Route::get('/my-profile', [ProfileController::class, 'myProfile'])->name('my-profile');

Route::post('post/comment/{id}', [ProductController::class, 'store'])
        ->name('post.comment');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.bunny.net/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Scripts -->
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    </head>
    <body class="font-sans antialiased">
        <div class="min-h-screen bg-gray-100">
            @include('layouts.navigation')

            <!-- Page Heading -->
            @if (isset($header))
                <header class="bg-white shadow">
                    <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
                        {{ $header }}
                    </div>
                </header>
            @endif

            <!-- Page Content -->
            <main>
                {{ $slot }}
            </main>
        </div>
    </body>
</html>

resources/views/layouts/css.blade.php
<link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
<!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"> -->

resources/views/layouts/footer.blade.php
<footer >
    <div class="">
        <nav class="flex mx-24 my-1 bg-blue-50">
            <ul class="ml-32 w-1/3 my-5">
                <li>Tích điểm quà tặng VIP</li>
                <li>Lịch sử mua hàng</li>
                <li>Tìm hiểu về mua trả góp</li>
                <li>Chính sách bảo hanh</li>
            </ul>
            <ul class="ml-32 w-1/3 my-5">
                <li>Giới thiệu công ty</li>
                <li>Tuyển dụng</li>
                <li>Gửi góp ý, khiếu nại</li>
                <li>Tìm siêu thị</li>
            </ul>
            <ul class=" w-1/3 my-5">
                <li class=" font-bold">Tổng đài hỗ trợ</li>
                <li>Gọi mua: 18009999 (7:30 - 22:00)</li>
                <li>Kỹ thuật: 18008888 (7:00 - 23:00)</li>
                <li>Bảo hành: 18007777 (8:00 - 20:00)</li>
            </ul>
        </nav>
    </div>
</footer>

resources/views/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>{{ config('app.name', 'Laravel') }}</title>

        <!-- Fonts -->
        <link rel="stylesheet" href="https://fonts.bunny.net/css2?family=Nunito:wght@400;600;700&display=swap">

        <!-- Scripts -->
        @vite(['resources/css/app.css', 'resources/js/app.js'])
    </head>
    <body>
        <div class="font-sans text-gray-900 antialiased">
            {{ $slot }}
        </div>
    </body>
</html>

resources/views/layouts/header.blade.php
<header>
    <div class=" ">
        <nav class="flex justify-between items-center  bg-yellow-400">
            <div class="flex ml-10">
                <img class="w-24 " src="/logo/logo.png" alt="">
                <h1 class="text-6xl m-5 ml-28 font-mono">NHA MOBILE</h1>
            </div>
            <ul class="flex justify-between items-center py-5">
                <div class="flex">
                    <img class="w-12 " src="/icon/home1.png" alt="">
                    <li class=" mt-3 text-xl"><a href="{{ route('home.index') }}">Trang chủ</a></li>
                </div>
                <div class="flex ml-12">
                    <img class="w-5 h-5 mt-3 " src="/icon/history.png" alt="">
                    <li class=" mt-2 ml-3 text-xl"><a href="{{ route('home.index') }}">Lịch sử</a></li>
                </div><div class="flex ml-12">
                    <img class="w-10 h-5 mt-2 " src="/icon/shopping1.png" alt="">
                    <li class=" mt-1 text-xl"><a href="cart">Giỏ hàng</a></li>
                </div><div class="flex ml-12 mr-16">
                @include('layouts.login')
                </div>
                
                
            </ul>
        </nav>
        
        <div class="flex">
            <img class="w-1/3 " src="https://images.fpt.shop/unsafe/fit-in/800x300/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2022/10/24/638021695897481292_F-H1_800x300.png" alt="">
            <img class="w-1/3 " src="https://images.fpt.shop/unsafe/fit-in/800x300/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2022/10/4/638004801120320356_F-H1_800x300.png" alt="">
            <img class="w-1/3" src="https://images.fpt.shop/unsafe/fit-in/800x300/filters:quality(90):fill(white)/fptshop.com.vn/Uploads/Originals/2022/10/15/638014290717253928_F-H1_800x300.png" alt="">
        </div>
        
        
        
            
        <div class="mx-24  bg-black h-24 mt-3">
            
        <div class=" bg-black text-xl w-96 h-12 ml-7">
            <form action="{{ route('product.index') }}" method="GET">
                <div class=" mb-3 flex">
                    <div >
                        <input type="text" name="keyword" value="{{ request()->get('keyword') }}" class=" m-3" placeholder="Tìm kiếm ">
                    </div>
                    <div class=" text-xl">
                    <button type="submit" class="  bg-blue-600 m-3 text-white" ><span class=""></span><span class="m-3">Tìm kiếm</span></button>
                    </div>        
                </div>
            </form>
        </div>
            <ul class="flex text-white ">
                <li class="ml-10 mr-5 mt-3"><a href="{{ route('home.index') }}">ĐIỆN THOẠI</a></li>
                <li class="mx-5 mt-3"><a href="#">LAPTOP</a></li>
                <li class="mx-5 mt-3"><a href="#">MÁY TÍNH BẢNG</a></li>
                <li class="mx-5 mt-3"><a href="#">APPLE</a></li>
                <li class="mx-5 mt-3"><a href="#">PC - LINH KIỆN</a></li>
                <li class="mx-5 mt-3"><a href="#">PHỤ KIỆN</a></li>
                <li class="mx-5 mt-3"><a href="#">MÁY CỦ GIÁ RẺ</a></li>
                <li class="mx-5 mt-3"><a href="#">HÀNG GIA DỤNG</a></li>
                <li class="mx-5 mt-3"><a href="#">SIM - THẺ</a></li>
                <li class="mx-5 mt-3"><a href="#">KHUYẾN MÃI</a></li>
                
            </ul>
            
        </div>
    </div>
</header>

resources/views/layouts/js.blade.php
{{-- declare all file script use global --}}
<script src="/plugins/jquery.min.js"></script>
<script src="/plugins/popper.min.js"></script>
<script src="/plugins/bootstrap/js/bootstrap.min.js"></script>

{{-- toastr --}}
<script src="/plugins/toastr/toastr.min.js"></script>

{{-- format number --}}
<script src="/plugins/jquery-number/jquery.number.min.js"></script>

<!-- declare variable global -->
<script>
    const BASE_URL = "{{ url('/') }}";
</script>

<script src="/js/common.js"></script>

{{-- declare other file script use private --}}
@stack('js')

resources/views/layouts/login.blade.php
@auth
    <!-- <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle shadow-none" type="button" 
        id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
            <span class="fa fa-user"></span>&nbsp;
            <span class="text">Xin chào,&nbsp;</span><span>{{ Auth::user()->name }}</span>
        </button>
        <ul class="dropdown-menu account-info" aria-labelledby="dropdownMenuButton1">
            <li><a class="dropdown-item active" href="{{ route('my-profile') }}"><i class="fa fa-info" aria-hidden="true"></i>&nbsp;
                Thông tin tài khoản</a></li>
            <li>
                <hr class="dropdown-divider">
            </li>
            <li><a class="dropdown-item" href=""><i class="fa fa-history" aria-hidden="true"></i>&nbsp;
                Lịch sử mua hàng</a></li>
            <li>
                <hr class="dropdown-divider">
            </li>
            <li><a class="dropdown-item" href=""><i class="fa fa-key" aria-hidden="true"></i>&nbsp;
                Đổi mật khẩu</a></li>
            <li>
                <hr class="dropdown-divider">
            </li>
            <li>
                <form action="{{ route('logout') }}" method="POST">
                    @csrf
                    <button type="submit" class="btn"><i class="fas fa-sign-out-alt"></i>&nbsp;
                        <span class="text">Logout</span></button>
                </form>
            </li>
        </ul>
    </div> -->
    <div class="flex justify-center">
  <div>
    <div class="dropdown relative">
      <button
        class="dropdown-toggle px-6 py-2.5 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded 
        shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none 
        focus:ring-0 active:bg-blue-800 active:shadow-lg active:text-white transition duration-150 ease-in-out 
        flex items-center whitespace-nowrap" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false"><span class="text">Xin chào,&nbsp;</span><span>{{ Auth::user()->name }}</span>
        <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="caret-down" class="w-2 ml-2"role="img"xmlns="http://www.w3.org/2000/svg"viewBox="0 0 320 512">
            <path fill="currentColor" d="M31.3 192h257.3c17.8 0 26.7 21.5 14.1 34.1L174.1 354.8c-7.8 7.8-20.5 7.8-28.3 0L17.2 226.1C4.6 213.5 13.5 192 31.3 192z"></path>
        </svg>
      </button>
      <ul class="dropdown-menu min-w-max absolute bg-white text-base z-50 float-left py-2 list-none text-left rounded-lg shadow-lg mt-1 hidden m-0 bg-clip-padding border-none" aria-labelledby="dropdownMenuButton1">
        <li>
          <a class="dropdown-item text-sm py-2 px-4 font-normal block w-full whitespace-nowrap bg-transparent text-gray-700 hover:bg-gray-100 "href="#" >&nbsp; Thông tin tài khoản</a>
        </li>
        <li>
          <a class="dropdown-item text-sm py-2 px-4 font-normal block w-full whitespace-nowrap bg-transparent text-gray-700 hover:bg-gray-100 "href="#" >&nbsp; Đổi mật khẩu</a>
        </li>
        <li>
          <a class="dropdown-item text-sm py-2 px-4 font-normal block w-full whitespace-nowrap bg-transparent text-gray-700 hover:bg-gray-100 "href="#" >
          <form action="{{ route('logout') }}" method="POST">
                    @csrf
                    <button type="submit" class="btn"><i class="fas fa-sign-out-alt"></i>&nbsp;
                        <span class="text">Logout</span></button>
                </form>
          </a>
        </li>
        
      </ul>
    </div>
  </div>
</div>
<li>
          <a class="dropdown-item text-sm py-2 px-4 font-normal block w-full whitespace-nowrap bg-transparent text-gray-700 hover:bg-gray-100 "href="#" >
          <form action="{{ route('logout') }}" method="POST">
                    @csrf
                    <button type="submit" class="btn"><i class="fas fa-sign-out-alt"></i>&nbsp;
                        <span class="text">Logout</span></button>
                </form>
          </a>
        </li>
@endauth
    
@guest

<div class="flex justify-center">
  <div>
    <div class="dropdown relative">
      <button
        class="dropdown-toggle px-6 py-2.5 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded 
        shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none 
        focus:ring-0 active:bg-blue-800 active:shadow-lg active:text-white transition duration-150 ease-in-out 
        flex items-center whitespace-nowrap" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">&nbsp;Tài khoản
        <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="caret-down" class="w-2 ml-2"role="img"xmlns="http://www.w3.org/2000/svg"viewBox="0 0 320 512">
            <path fill="currentColor" d="M31.3 192h257.3c17.8 0 26.7 21.5 14.1 34.1L174.1 354.8c-7.8 7.8-20.5 7.8-28.3 0L17.2 226.1C4.6 213.5 13.5 192 31.3 192z"></path>
        </svg>
      </button>
      <ul class="dropdown-menu min-w-max absolute bg-white text-base z-50 float-left py-2 list-none text-left rounded-lg shadow-lg mt-1 hidden m-0 bg-clip-padding border-none" aria-labelledby="dropdownMenuButton1">
        <li>
          <a class="dropdown-item text-sm py-2 px-4 font-normal block w-full whitespace-nowrap bg-transparent text-gray-700 hover:bg-gray-100 "href="{{ route('login') }}" >&nbsp; Đăng nhập</a>
        </li>
        <li>
          <a class="dropdown-item text-sm py-2 px-4 font-normal block w-full whitespace-nowrap bg-transparent text-gray-700 hover:bg-gray-100 "href="{{ route('register') }}" >&nbsp; Đăng ký</a>
        </li>
       
        
      </ul>
    </div>
  </div>
</div>
<li>
          <a class="dropdown-item text-sm py-2 px-4 font-normal block w-full whitespace-nowrap bg-transparent text-gray-700 hover:bg-gray-100 "href="{{ route('login') }}" >&nbsp; Đăng nhập</a>
        </li>

    <!-- <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle shadow-none" type="button" 
        id="dropdownMenuButton2" data-bs-toggle="dropdown" aria-expanded="false">
        <span class="fa fa-user"></span><span class="text">&nbsp;Tài khoản</span>
        </button>
        <ul class="dropdown-menu dropdown-menu-dark account-info" aria-labelledby="dropdownMenuButton2">
            <li><a class="dropdown-item" href="{{ route('login') }}"><i class="fa fa-user" aria-hidden="true"></i>&nbsp;
                Đăng nhập</a></li>
            <li>
                <hr class="dropdown-divider">
            </li>
            <li><a class="dropdown-item" href="{{ route('register') }}"><i class="fa fa-user-plus" aria-hidden="true"></i>&nbsp;
                Tạo tài khoản</a></li>
        </ul>
    </div> -->
    
@endguest


<!-- <div class="flex justify-center">
  <div>
    <div class="dropdown relative">
      <button
        class="dropdown-toggle px-6 py-2.5 bg-blue-600 text-white font-medium text-xs leading-tight uppercase rounded 
        shadow-md hover:bg-blue-700 hover:shadow-lg focus:bg-blue-700 focus:shadow-lg focus:outline-none 
        focus:ring-0 active:bg-blue-800 active:shadow-lg active:text-white transition duration-150 ease-in-out 
        flex items-center whitespace-nowrap" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">Dropdown button
        <svg aria-hidden="true" focusable="false" data-prefix="fas" data-icon="caret-down" class="w-2 ml-2"role="img"xmlns="http://www.w3.org/2000/svg"viewBox="0 0 320 512">
            <path fill="currentColor" d="M31.3 192h257.3c17.8 0 26.7 21.5 14.1 34.1L174.1 354.8c-7.8 7.8-20.5 7.8-28.3 0L17.2 226.1C4.6 213.5 13.5 192 31.3 192z"></path>
        </svg>
      </button>
      <ul class="dropdown-menu min-w-max absolute bg-white text-base z-50 float-left py-2 list-none text-left rounded-lg shadow-lg mt-1 hidden m-0 bg-clip-padding border-none" aria-labelledby="dropdownMenuButton1">
        <li>
          <a class="dropdown-item text-sm py-2 px-4 font-normal block w-full whitespace-nowrap bg-transparent text-gray-700 hover:bg-gray-100 "href="#" >Action</a>
        </li>
        <li>
          <a class="dropdown-item text-sm py-2 px-4 font-normal block w-full whitespace-nowrap bg-transparent text-gray-700 hover:bg-gray-100 "href="#" >Action</a>
        </li>
        <li>
          <a class="dropdown-item text-sm py-2 px-4 font-normal block w-full whitespace-nowrap bg-transparent text-gray-700 hover:bg-gray-100 "href="#" >Action</a>
        </li>
        
      </ul>
    </div>
  </div>
</div> -->

resources/views/layouts/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}" />
  
    



   
    <title>@yield('title', 'Home Page')</title>
    {{-- css --}}
    @include('layouts.css')
</head>
<body>
    {{-- header --}}
    @include('layouts.header')

    {{-- content --}}
    <main>
        <div class="container">
            @yield('content')
        </div>
    </main>

    {{-- footer --}}
    @include('layouts.footer')

    {{-- js --}}
    @include('layouts.js')
</body>
</html>

resources/views/layouts/navigation.blade.php
<nav x-data="{ open: false }" class="bg-white border-b border-gray-100">
    <!-- Primary Navigation Menu -->
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="flex justify-between h-16">
            <div class="flex">
                <!-- Logo -->
                <div class="shrink-0 flex items-center">
                    <a href="{{ route('dashboard') }}">
                        <x-application-logo class="block h-10 w-auto fill-current text-gray-600" />
                    </a>
                </div>

                <!-- Navigation Links -->
                <div class="hidden space-x-8 sm:-my-px sm:ml-10 sm:flex">
                    <x-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                        {{ __('Dashboard') }}
                    </x-nav-link>
                </div>
            </div>

            <!-- Settings Dropdown -->
            <div class="hidden sm:flex sm:items-center sm:ml-6">
                <x-dropdown align="right" width="48">
                    <x-slot name="trigger">
                        <button class="flex items-center text-sm font-medium text-gray-500 hover:text-gray-700 hover:border-gray-300 focus:outline-none focus:text-gray-700 focus:border-gray-300 transition duration-150 ease-in-out">
                            <div>{{ Auth::user()->name }}</div>

                            <div class="ml-1">
                                <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                    <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                                </svg>
                            </div>
                        </button>
                    </x-slot>

                    <x-slot name="content">
                        <!-- Authentication -->
                        <form method="POST" action="{{ route('logout') }}">
                            @csrf

                            <x-dropdown-link :href="route('logout')"
                                    onclick="event.preventDefault();
                                                this.closest('form').submit();">
                                {{ __('Log Out') }}
                            </x-dropdown-link>
                        </form>
                    </x-slot>
                </x-dropdown>
            </div>

            <!-- Hamburger -->
            <div class="-mr-2 flex items-center sm:hidden">
                <button @click="open = ! open" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:bg-gray-100 focus:text-gray-500 transition duration-150 ease-in-out">
                    <svg class="h-6 w-6" stroke="currentColor" fill="none" viewBox="0 0 24 24">
                        <path :class="{'hidden': open, 'inline-flex': ! open }" class="inline-flex" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
                        <path :class="{'hidden': ! open, 'inline-flex': open }" class="hidden" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
                    </svg>
                </button>
            </div>
        </div>
    </div>

    <!-- Responsive Navigation Menu -->
    <div :class="{'block': open, 'hidden': ! open}" class="hidden sm:hidden">
        <div class="pt-2 pb-3 space-y-1">
            <x-responsive-nav-link :href="route('dashboard')" :active="request()->routeIs('dashboard')">
                {{ __('Dashboard') }}
            </x-responsive-nav-link>
        </div>

        <!-- Responsive Settings Options -->
        <div class="pt-4 pb-1 border-t border-gray-200">
            <div class="px-4">
                <div class="font-medium text-base text-gray-800">{{ Auth::user()->name }}</div>
                <div class="font-medium text-sm text-gray-500">{{ Auth::user()->email }}</div>
            </div>

            <div class="mt-3 space-y-1">
                <!-- Authentication -->
                <form method="POST" action="{{ route('logout') }}">
                    @csrf

                    <x-responsive-nav-link :href="route('logout')"
                            onclick="event.preventDefault();
                                        this.closest('form').submit();">
                        {{ __('Log Out') }}
                    </x-responsive-nav-link>
                </form>
            </div>
        </div>
    </div>
</nav>